# Generated by Django 4.1.2 on 2022-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
